---

galaxy_info:
  author: zenoamaro
  description: A role for installing and configuring PostgreSQL
  license: MIT
  min_ansible_version: 1.4

  platforms:
    - name: Ubuntu
      versions:
        - precise

  categories:
    - database
    - database:sql

dependencies: []
