---
- hosts: all
  sudo: yes
  roles:
    - common
    - bash
    - role: nginx
      nginx_sites:
        - server:
            file_name: vagrant_ansible
            listen: 80
            server_name: localhost
            root: "/vagrant/public"
    - role: postgresql
      postgresql_dev_headers: yes
      postgresql_psycopg2: yes
      postgresql_postgis: yes
    - virtualenv
